{% set name = "insarscript" %}
{% set version = "1.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jldz9/InSARScript/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bbb4ba8d0e43dfd021212e90980f213a6bac82d6e09f0c25ba698619cda1d199

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - insarhub 

test: 
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - insarhub
  commands:
    - pip check

about:
  home: https://github.com/jldz9/InSARHub
  license: MIT
  license_file: LICENSE
  summary: "Hassle-free InSAR processing scripts for multiple satellites"
  description: |
    This package is deprecated. Please use `insarhub` instead:
    conda install -c conda-forge insarhub
  doc_url: https://jldz9.github.io/InSARHub/


extra:
  recipe-maintainers:
    - jldz9
  deprecated: true
